version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli
    environment:
      - APACHE_FILE_PROXY

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro
    environment:
      - THEME_ROOT

  # Fake email
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail

  # PHPMyAdmin
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
